# Generated by Django 3.0.2 on 2020-01-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
